/*
 * Mavlink is a protocol used in internal communication on UAVs.
 *
 * Uses parts from the autogenerated code from our own message definitions.
 *
 * Copyright (C) 2020 by Alexander Hedges (alexander.hedges@fotokite.com)
 *
 * Licensed under the GPL v2 or later
 */

#if defined(CONFIG_CMD_MAVLINK)

#ifndef __MAVLINK_H__
#define __MAVLINK_H__

#include <common.h>

void mavlink_start(void);

#endif /* __MAVLINK_H__ */
#endif
